# Generated by Django 5.1.1 on 2024-09-19 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_of_division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Manufactured_date', models.DateField(null=True)),
                ('cost', models.PositiveIntegerField()),
                ('invoice', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('COMP', 'Computer'), ('LAPT', 'LAPTOP'), ('SERV', 'SERVER'), ('UPS', 'UPS'), ('PROJ', 'PROJECTOR'), ('ACP', 'ACCESS POINT'), ('BMD', 'BIOMETRIC DEVICE'), ('PRIN', 'Printer'), ('PHOTO', 'Photocopy Machine'), ('MEZA', 'MEZA'), ('KAB', 'KABATI'), ('KIT', 'KITI'), ('SOF', 'SOFA'), ('OTHERS', 'Other Accessories')], max_length=10)),
                ('specification', models.CharField(blank=True, max_length=700, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Received_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('asset_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('asset_status', models.CharField(choices=[('A', 'Active'), ('B', 'Need Troubleshoot'), ('C', 'Inactive')], default='A', max_length=1)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('useful_life', models.IntegerField(default=5)),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_to_division', to='asset_mgt_app.division')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('details', models.CharField(max_length=200)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_mgt_app.asset')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division', to='asset_mgt_app.office'),
        ),
    ]
