# Generated by Django 5.1 on 2024-09-04 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('head_of_division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('Manufactured_date', models.DateField(blank=True, null=True)),
                ('cost', models.PositiveIntegerField()),
                ('invoice', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('FURN', 'Furniture'), ('COMP', 'Computer'), ('PRIN', 'Printer'), ('PHOTO', 'Photocopy Machine'), ('OTHERS', 'Other Accessories')], max_length=10)),
                ('specification', models.CharField(blank=True, max_length=150, null=True)),
                ('model_number', models.CharField(blank=True, max_length=50, null=True)),
                ('Received_date', models.DateTimeField(auto_now_add=True)),
                ('asset_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('A', 'Active'), ('B', 'Need Troubleshoot'), ('C', 'Inactive')], default='A', max_length=1)),
                ('depreciation', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('useful_life', models.IntegerField(default=5)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_to_division', to='asset_mgt_app.division')),
            ],
        ),
        migrations.CreateModel(
            name='Maintainance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('details', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asset_mgt_app.asset')),
            ],
        ),
        migrations.AddField(
            model_name='division',
            name='office',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='division', to='asset_mgt_app.office'),
        ),
    ]
