# Generated by Django 5.1 on 2024-09-05 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='Manufactured_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='category',
            field=models.CharField(choices=[('COMP', 'Computer'), ('PRIN', 'Printer'), ('PHOTO', 'Photocopy Machine'), ('MEZA', 'MEZA'), ('KAB', 'KABATI'), ('KIT', 'KITI'), ('SOF', 'SOFA'), ('OTHERS', 'Other Accessories')], max_length=10),
        ),
    ]
