# Generated by Django 5.1.1 on 2024-09-25 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgt_app', '0002_pendingaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingaction',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
