# Generated by Django 5.1 on 2024-09-05 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgt_app', '0003_alter_asset_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Maintainance',
            new_name='Maintenance',
        ),
    ]
