# Generated by Django 5.1.1 on 2024-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgt_app', '0003_pendingaction_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_pending',
            field=models.BooleanField(default=False),
        ),
    ]
