# Generated by Django 5.1.1 on 2024-09-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgt_app', '0004_asset_is_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='pending_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
