# Generated by Django 5.1.1 on 2024-09-26 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgt_app', '0005_asset_pending_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='pending_description',
        ),
    ]
