# Generated by Django 5.1.1 on 2024-09-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_mgt_app', '0006_remove_asset_pending_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_updated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='pendingAndUpdated_desc',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
